[package]
name = "gluer"
version = "0.8.3"
edition = "2021"
authors = ["Nils Wrenger <nils@wrenger.net>"]
description = "A wrapper for Rust frameworks that eliminates redundant type and function definitions between the frontend and backend"
keywords = ["parser", "api", "macro"]
categories = ["accessibility", "web-programming", "api-bindings"]
rust-version = "1.61.0"
repository = "https://github.com/nwrenger/gluer"
readme = "README.md"
license = "GPL-3.0-or-later"

[lib]
proc-macro = true

[dependencies]
quote = "1.0.37"
syn = { version = "2.0.90", features = ["full"] }
proc-macro2 = "1.0.92"

[dev-dependencies]
axum = "0.7.9"
tokio = { version = "1.42.0", features = ["macros", "rt-multi-thread"] }
serde = { version = "1.0.216", features = ["derive"] }
